services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

#  db:
#    image: mysql:8.4.2
#    ports:
#      - "32000:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ./db:/docker-entrypoint-initdb.d/:ro
